### ISSUE TITLE
Open toggle buttons when printing

### ISSUE THREAD

**Issue by DavidPowell** [executablebooks/sphinx-togglebutton#14]
When printing pages containing this toggle button (e.g. printing a page created with Jupyter-book using the download PDF button), any toggled contents remain hidden, unless manually toggled

For my use case it would make sense to show all content when printing, I would expect this would be the case for most other users.

**Comment by choldgraf** [comment]
I think that makes sense - the thing to do would be to add a `print` rule here: https://github.com/executablebooks/sphinx-togglebutton/blob/master/sphinx_togglebutton/_static/togglebutton.css_t

and forcibly display the toggled content. I guess the other thing we could do is add some JS to remove the "toggle" class when "print" is clicked, but that feels a bit hackier

**Comment by DavidPowell** [comment]
Thanks for hints, and sorry for very much delayed response. 

As far as I can see, what is required is to just turn off all CSS when print media is used. This is exactly what I have done in this commit: https://github.com/DavidPowell/sphinx-togglebutton/commit/e2d84f6f0e3f2fab666fc073eeabb359480051d5.

I have limited knowledge of CSS, so I don't know if there are any unintended side-effects. If it's okay, I'll submit a PR.
