### ISSUE TITLE
Stylesheet togglebutton.css not rendered

### ISSUE THREAD

**Issue by hroemer** [executablebooks/sphinx-togglebutton#18]
**Describe the bug**

The extension is not working out-of-the box as the according CSS file does not get added to the HTML header.

**To Reproduce**

Follow the instructions in [README.md](../blob/master/README.md)

**Environment**

- Python Version 3.8.5
- Package versions: 0.2.2
- Operating System: Linux

**Additional context**

The reason is that the `config.html_context` is not filled accordingly , ~~probably due to a premature call to `app.add_css_file("togglebutton.css")`.~~

Adding these lines:

```python
def add_to_context(app, config):
    # Update the global context
    config.html_context.update({"togglebutton_hint": config.togglebutton_hint})

    if not config.html_context["css_files"]:
        config.html_context["css_files"] = []
    config.html_context["css_files"].append('_static/togglebutton.css')
```
and renaming the file `togglebutton.css_t` (!?) in the _static folder to the expected file named `togglebutton.css` fixes the problem.

**Comment by hroemer** [comment]
As a follow up: I read about [Sphinx static templates](https://www.sphinx-doc.org/en/master/development/theming.html#static-templates#theming-static-templates) and I can now strike out the ``*.css_t`` from the equation. Thus it is not necessary to rename the file, the template engine will do anyway.

It tested with default `alabaster` theme and `sphinx_book_theme` under a clean virtual environment, but still cannot get it to run from scratch. I need to add these lines:

```python
if not config.html_context["css_files"]:
        config.html_context["css_files"] = []
config.html_context["css_files"].append('_static/togglebutton.css')
```
Otherwise the required ``<head><style>...`` reference will not be added to the rendered page.

Any help really appreciated.

**Comment by choldgraf** [comment]
Hey - sorry for the slow response, am dealing with a newborn baby :-)

That's weird that you don't see the CSS file in the header. It should be added with this line here:

https://github.com/executablebooks/sphinx-togglebutton/blob/master/sphinx_togglebutton/__init__.py#L53

what version of Sphinx are you running?

Also, in case it's helpful, you may also want to check out `sphinx-panels` (https://sphinx-panels.readthedocs.io/en/latest/#dropdown-usage) which has a similar "dropdown" functionality

**Comment by hroemer** [comment]
No worries and congratulations for your newborn baby :fireworks:  

I am using the latest Sphinx version 3.2.1, but it is still not working.
Thanks for pointing me to `sphinx-panels`, it is working great thus far and covers exactly what I was looking for :+1:

**Comment by choldgraf** [comment]
I'm closing this one as it sounds like sphinx-panels has worked out well for you, and I haven't had any reports from others that this isn't working in sphinx-togglebutton. Feel free to re-open or post a new issue if there's still a problem
