### ISSUE TITLE
Update sphinx-collapse-admonitions to point to here

### ISSUE THREAD

**Issue by rkdarst** [executablebooks/sphinx-togglebutton#20]
https://github.com/choldgraf/sphinx-collapse-admonitions could be updated (the "about" on the side for example, better yet the readme) to point to here.  I found that, noticed it was archived, didn't use it, and spent several days searching for something else that was active.  Only today I realized I should check sphinx-book-theme's dependencies for clues, and found this which is exactly what I wanted.

(perhaps related, throw in the word "collapse" to these docs somewhere, so that it's more findable?  I couldn't think of the right term to find this project...)

Thanks for making this!

**Comment by choldgraf** [comment]
Hmmm good point about the other repo - I actually just decided to delete it.

re: this package, I agree that adding "collapse" in here would be helpful
