### ISSUE TITLE
Isn't z-index: 999 a bit excessive?

### ISSUE THREAD

**Issue by mgeier** [executablebooks/sphinx-togglebutton#23]
I don't know what the conventions are around this, but 999 seems a bit high to me.

The highest value mentioned at https://developer.mozilla.org/en-US/docs/Web/CSS/z-index is 289.

And at https://drafts.csswg.org/css2/#propdef-z-index it seems to be 3.

Wouldn't something like 99 be more reasonable?

Right now, this is in conflict with [my Sphinx theme](https://insipid-sphinx-theme.readthedocs.io/). I could of course raise my conflicting `z-index`, but when does the arms race end?

**Comment by choldgraf** [comment]
absolutely - 999 is a 💯 hack job that was just trying to get it to reliably work. I don't know anything about the "proper" conventions for z-index but I'm open to using whatever number makes the most sense for most users.

**Comment by mgeier** [comment]
> just trying to get it to reliably work

The problem is that it doesn't.

I guess there is no perfect solution because we don't know all past and future Sphinx themes.

But what about starting with 100?

**Comment by mgeier** [comment]
The RTD version badge uses 400, so you should probably aim below that:

![image](https://user-images.githubusercontent.com/705404/96698912-f401b080-138d-11eb-8d57-538156e6479d.png)

**Comment by choldgraf** [comment]
100 makes sense to me - I'm on reduced time right now due to a newborn, but happy to review a PR to see if that fixes it. Otherwise I will try and get to this later this / next week

**Comment by mgeier** [comment]
Sounds good, there's no hurry!
