### ISSUE TITLE
Use a different word than "toggle"?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-togglebutton#3]
I think many people often use the word "hide" to describe what this repository calls "toggle" (e.g. to remove content from view, but with a button to show it). Perhaps we should think of re-using "hide" rather than "toggle" in configuration?

E.g., allow for following:

````
```{note}
:class: hide

My note
```
````

Instead of

````
```{note}
:class: toggle

My note
```
````

The concern I have is that this will class with other CSS, since `hide` is a common word.

**Comment by mgeier** [comment]
I think "toggle" fits perfectly.

**Comment by choldgraf** [comment]
yeah, I have come around to `toggle` as well, and for some reason "hidebutton" feels awkard to me. I'll close this and we can leave it at toggle
