### ISSUE TITLE
Toggle hint is inserted into code blocks when clicking inside them

### ISSUE THREAD

**Issue by janssenhenning** [executablebooks/sphinx-togglebutton#44]
### Describe the bug

**context**
When a `code-block` is nested inside a toggle region and one clicks inside this block the toggle hint, i.e. `Click to show` or `Click to hide` is inserted into the beginning of the block

These two screenshots are form the sphinx-togglebutton read the docs page
Before clicking into the code block

<img width="761" alt="Screenshot 2022-06-20 at 14 22 56" src="https://user-images.githubusercontent.com/11249470/174600836-dc8d6233-b5b1-4e6f-b64f-c73d87653a9b.png">
And after
<img width="761" alt="Screenshot 2022-06-20 at 14 23 14" src="https://user-images.githubusercontent.com/11249470/174600840-799357bc-7fd1-489f-ba02-7ac05a84c6a8.png">

### Reproduce the bug

1. Go to https://sphinx-togglebutton.readthedocs.io/en/latest/ for example
2. Click the first toggle button
3. Click inside the revealed code block

**Comment by choldgraf** [comment]
closed by https://github.com/executablebooks/sphinx-togglebutton/pull/45
