### ISSUE TITLE
Update togglebutton style to be more minimal and resemble Jupyter Lab UI/UX

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-togglebutton#46]
### Context

Currently, we have a fairly standard "button" UI for the `toggle` directive:

![chrome_JGjTUJtlhc](https://user-images.githubusercontent.com/1839645/176648005-0fa96ce2-cd82-44c1-966e-cf0afafe321f.gif)

This works fine, though has a fairly "basic" button style.

### Proposal

I wanted to see what it might look like for us to re-work this button UI with a few guiding principles:

- Make it more minimal, and reduce the amount of "ink" used in general
- Make it look more similar to the show/hide behavior from Jupyter Notebooks / Lab (since this project is used in conjunction with myst-nb quite often).

I put together this quick prototype with very few CSS changes. Curious if others think this would be an improvement on our current UI:

![chrome_hAm06EevXq](https://user-images.githubusercontent.com/1839645/176648318-37e269dc-638a-48b7-be06-f60e7bd22ac5.gif)

Alternatively, this might be styling that other themes could implement themselves, if this seems too "opinionated" for a base extension...

**Comment by choldgraf** [comment]
cc @mmcky @janssenhenning @tfiers and @kloczek who have recently opened issues in this repo, which suggests to me they are actually using this extension 😅

**Comment by tfiers** [comment]
I agree with the principles and the proposal looks good!

**Comment by choldgraf** [comment]
Given the generally positive initial feedback, I decided to give this a shot at implementing, so feel free to also provide feedback here:

- https://github.com/executablebooks/sphinx-togglebutton/pull/47
